### ISSUE TITLE
How does customize.lua work? Random questions

### ISSUE THREAD

**Issue by rieje** [Traap/nvim#2]
Disclaimer: new to lua (and programming):

Came across your video on Neovim and was wondering how does customize.lua work to quickly disable/enable plugins for testing. I know in your utilities.lua you have e.g. `return require('traap.core.customize').harpoon` for all the relevant plugins and that customize.lua contains a list of your plugins, but not sure how the `return require(...).plugin` works, e.g. whether it has to do with lua, Neovim, or both.

Also, do you see any reason to use after/ directories (e.g. ~/.config/nvim/after/plugin/telescope.lua) in runtimepath? I believe those are loaded after plugins are loaded so they should ensure nothing gets overwritten although I know you explicitly defined the order yourself. I briefly used Neovim about 2 years ago and it was popular for people to dump all their files in ~/.config/nvim/lua/personal_namespace but now it seems after/ directories are more common.

Lastly curious if utilizing lua to make code in config prettier has the potential to affect performance, e.g. in your options.lua config, you have a table of options and then at the end iterate through each to set them. Or e.g. splitting what would have been a large init.lua file into many configs, like one for each plugin which is popular.

Thanks and looking forward to more videos.

**Comment by Traap** [comment]
> Came across your video on Neovim ...

Hi rieje - First!  Thank you for watching my video and taking time to ask me a question. 

>  and was wondering how does customize.lua work to quickly disable/enable plugins for testing. I know in your utilities.lua you have e.g. `return require('traap.core.customize').harpoon` for all the relevant plugins 

enabled = [ true | false ] is runtime equivalent  the function that does 'return require('traap.core.customize').harpoon.  LuaJIT (just in time compiler) does optimize.

I may update the code to something like:

  local customize = require('traap.core.customzie')

which becomes an "alias" so require statement only appears once in the code.  LuaJIT still has to do work and can optimize away.   Then all enabled = function() could change to enabled = customize.harpoon, as an example.



> and that customize.lua contains a list of your plugins, but not sure how the `return require(...).plugin` works, e.g. whether it has to do with lua, Neovim, or both.

This is lua syntax.  It is essentially returning true or false.

> Also, do you see any reason to use after/ directories (e.g. ~/.config/nvim/after/plugin/telescope.lua) in runtimepath? 

The Lazy package manager  loads all plugins define in the specification found in traap.core.plugins.  I tell Lazy to load files found at traap.plugins.  Lazy process these files alphabetically.    Neovim will load after/plugin/... files alphabetically  too which is okay.  The caveat to remember referencing any plugin before it is loaded will cause a failure.  

I just posted a pull-request https://github.com/Traap/init.lua to ThePrimeagen to resolve the caveat I just mentioned.  If you want to use after/plugin/... just remember to use the pcall(requrie, 'harpoon') syntax.  

> I believe those are loaded after plugins are loaded so they should ensure nothing gets overwritten although I know you explicitly defined the order yourself. 

You are correct.

> I briefly used Neovim about 2 years ago ...

Welcome back.

> and it was popular for people to dump all their files in ~/.config/nvim/lua/personal_namespace but now it seems after/ directories are more common.

I see both techniques done.  I see rational for using either method or both.
 
> Lastly curious if utilizing lua to make code in config prettier has the potential to affect performance, e.g. in your options.lua config, you have a table of options and then at the end iterate through each to set them. Or e.g. splitting what would have been a large init.lua file into many configs, like one for each plugin which is popular.

I merged most plugins into traap.plugins.utilities for two reasons.   
1.  I was implementing the customize flag for each plugin.  
2.  To "show off" the vim folding sytle I use.

> Thanks and looking forward to more videos.

I am working content for my next Video now.  I  will demonstrate "neovim starter kit swapping."  That is the primary reason I wanted made a pull-request for ThePrimeagen.  Prime uses packer and lsp-zero, which is cool.  I want to show between my configuration and others without "fear of destroying" your Neovim environment.
