### ISSUE TITLE
File location

### ISSUE THREAD

**Issue by waldirborbajr** [Traap/nvim#4]
Hi,
I'm studying your config and adding some items to my config. Now I'm facing with this lines, 
      require("lazyvim.util").on_attach(function(client, buffer)
        require("lazyvim.plugins.lsp.format").on_attach(client, buffer)
        require("lazyvim.plugins.lsp.keymaps").on_attach(client, buffer)

and I'm trying to decifrate where lazyvim.plugins.lsp.format it is. Could your please show me the way.

Before I go, let me thank you for videos about lazy I'm loving and learning and adapting my config.

**Comment by waldirborbajr** [comment]
Got it... it is a plugin that I must install ... 

	{ "LazyVim/LazyVim", import = "lazyvim.plugins" },

**Comment by Traap** [comment]
Glad you found it.
