### ISSUE TITLE
 switchNeovim link is broken

### ISSUE THREAD

**Issue by voyeg3r** [Traap/nvim#5]
Please fix your [switchNeovim](https://github.com/Traap/dotfiles/blob/master/bin/switchNeovim) link. So I can also use it!

**Comment by Traap** [comment]
Problem fixed.  Thank you for point out the error.

**Comment by mrs4ndman** [comment]
The link for Folke's profile is also broken ;).
Sorry for the intrusion

**Comment by Traap** [comment]
Folke's url is fixed.  Moves directly to his GitHub page.  Thank  you for reporting the error.
